// Generated by gencpp from file task/Io.msg
// DO NOT EDIT!


#ifndef TASK_MESSAGE_IO_H
#define TASK_MESSAGE_IO_H

#include <ros/service_traits.h>


#include <task/IoRequest.h>
#include <task/IoResponse.h>


namespace task
{

struct Io
{

typedef IoRequest Request;
typedef IoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Io
} // namespace task


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::task::Io > {
  static const char* value()
  {
    return "e485b43c04e16f65a9831427eefda836";
  }

  static const char* value(const ::task::Io&) { return value(); }
};

template<>
struct DataType< ::task::Io > {
  static const char* value()
  {
    return "task/Io";
  }

  static const char* value(const ::task::Io&) { return value(); }
};


// service_traits::MD5Sum< ::task::IoRequest> should match
// service_traits::MD5Sum< ::task::Io >
template<>
struct MD5Sum< ::task::IoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::task::Io >::value();
  }
  static const char* value(const ::task::IoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::task::IoRequest> should match
// service_traits::DataType< ::task::Io >
template<>
struct DataType< ::task::IoRequest>
{
  static const char* value()
  {
    return DataType< ::task::Io >::value();
  }
  static const char* value(const ::task::IoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::task::IoResponse> should match
// service_traits::MD5Sum< ::task::Io >
template<>
struct MD5Sum< ::task::IoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::task::Io >::value();
  }
  static const char* value(const ::task::IoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::task::IoResponse> should match
// service_traits::DataType< ::task::Io >
template<>
struct DataType< ::task::IoResponse>
{
  static const char* value()
  {
    return DataType< ::task::Io >::value();
  }
  static const char* value(const ::task::IoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TASK_MESSAGE_IO_H
