// Generated by gencpp from file task/IoResponse.msg
// DO NOT EDIT!


#ifndef TASK_MESSAGE_IORESPONSE_H
#define TASK_MESSAGE_IORESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace task
{
template <class ContainerAllocator>
struct IoResponse_
{
  typedef IoResponse_<ContainerAllocator> Type;

  IoResponse_()
    : now_state(false)  {
    }
  IoResponse_(const ContainerAllocator& _alloc)
    : now_state(false)  {
  (void)_alloc;
    }



   typedef uint8_t _now_state_type;
  _now_state_type now_state;





  typedef boost::shared_ptr< ::task::IoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::task::IoResponse_<ContainerAllocator> const> ConstPtr;

}; // struct IoResponse_

typedef ::task::IoResponse_<std::allocator<void> > IoResponse;

typedef boost::shared_ptr< ::task::IoResponse > IoResponsePtr;
typedef boost::shared_ptr< ::task::IoResponse const> IoResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::task::IoResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::task::IoResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::task::IoResponse_<ContainerAllocator1> & lhs, const ::task::IoResponse_<ContainerAllocator2> & rhs)
{
  return lhs.now_state == rhs.now_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::task::IoResponse_<ContainerAllocator1> & lhs, const ::task::IoResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace task

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::task::IoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::task::IoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::task::IoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::task::IoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task::IoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task::IoResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::task::IoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f5411d3955ab1f2c1ec1dc6ae762707f";
  }

  static const char* value(const ::task::IoResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf5411d3955ab1f2cULL;
  static const uint64_t static_value2 = 0x1ec1dc6ae762707fULL;
};

template<class ContainerAllocator>
struct DataType< ::task::IoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "task/IoResponse";
  }

  static const char* value(const ::task::IoResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::task::IoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool now_state\n"
;
  }

  static const char* value(const ::task::IoResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::task::IoResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.now_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IoResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::task::IoResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::task::IoResponse_<ContainerAllocator>& v)
  {
    s << indent << "now_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.now_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TASK_MESSAGE_IORESPONSE_H
