// Generated by gencpp from file task/Pwm.msg
// DO NOT EDIT!


#ifndef TASK_MESSAGE_PWM_H
#define TASK_MESSAGE_PWM_H

#include <ros/service_traits.h>


#include <task/PwmRequest.h>
#include <task/PwmResponse.h>


namespace task
{

struct Pwm
{

typedef PwmRequest Request;
typedef PwmResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Pwm
} // namespace task


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::task::Pwm > {
  static const char* value()
  {
    return "2cf059adcc761a1dfe88251e9a131afb";
  }

  static const char* value(const ::task::Pwm&) { return value(); }
};

template<>
struct DataType< ::task::Pwm > {
  static const char* value()
  {
    return "task/Pwm";
  }

  static const char* value(const ::task::Pwm&) { return value(); }
};


// service_traits::MD5Sum< ::task::PwmRequest> should match
// service_traits::MD5Sum< ::task::Pwm >
template<>
struct MD5Sum< ::task::PwmRequest>
{
  static const char* value()
  {
    return MD5Sum< ::task::Pwm >::value();
  }
  static const char* value(const ::task::PwmRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::task::PwmRequest> should match
// service_traits::DataType< ::task::Pwm >
template<>
struct DataType< ::task::PwmRequest>
{
  static const char* value()
  {
    return DataType< ::task::Pwm >::value();
  }
  static const char* value(const ::task::PwmRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::task::PwmResponse> should match
// service_traits::MD5Sum< ::task::Pwm >
template<>
struct MD5Sum< ::task::PwmResponse>
{
  static const char* value()
  {
    return MD5Sum< ::task::Pwm >::value();
  }
  static const char* value(const ::task::PwmResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::task::PwmResponse> should match
// service_traits::DataType< ::task::Pwm >
template<>
struct DataType< ::task::PwmResponse>
{
  static const char* value()
  {
    return DataType< ::task::Pwm >::value();
  }
  static const char* value(const ::task::PwmResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TASK_MESSAGE_PWM_H
