// Generated by gencpp from file task/PwmResponse.msg
// DO NOT EDIT!


#ifndef TASK_MESSAGE_PWMRESPONSE_H
#define TASK_MESSAGE_PWMRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace task
{
template <class ContainerAllocator>
struct PwmResponse_
{
  typedef PwmResponse_<ContainerAllocator> Type;

  PwmResponse_()
    : now_duty(0.0)  {
    }
  PwmResponse_(const ContainerAllocator& _alloc)
    : now_duty(0.0)  {
  (void)_alloc;
    }



   typedef float _now_duty_type;
  _now_duty_type now_duty;





  typedef boost::shared_ptr< ::task::PwmResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::task::PwmResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PwmResponse_

typedef ::task::PwmResponse_<std::allocator<void> > PwmResponse;

typedef boost::shared_ptr< ::task::PwmResponse > PwmResponsePtr;
typedef boost::shared_ptr< ::task::PwmResponse const> PwmResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::task::PwmResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::task::PwmResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::task::PwmResponse_<ContainerAllocator1> & lhs, const ::task::PwmResponse_<ContainerAllocator2> & rhs)
{
  return lhs.now_duty == rhs.now_duty;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::task::PwmResponse_<ContainerAllocator1> & lhs, const ::task::PwmResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace task

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::task::PwmResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::task::PwmResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::task::PwmResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::task::PwmResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task::PwmResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task::PwmResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::task::PwmResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ff49f11ebd4122f9f5382535bfb1800";
  }

  static const char* value(const ::task::PwmResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ff49f11ebd4122fULL;
  static const uint64_t static_value2 = 0x9f5382535bfb1800ULL;
};

template<class ContainerAllocator>
struct DataType< ::task::PwmResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "task/PwmResponse";
  }

  static const char* value(const ::task::PwmResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::task::PwmResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 now_duty\n"
;
  }

  static const char* value(const ::task::PwmResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::task::PwmResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.now_duty);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PwmResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::task::PwmResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::task::PwmResponse_<ContainerAllocator>& v)
  {
    s << indent << "now_duty: ";
    Printer<float>::stream(s, indent + "  ", v.now_duty);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TASK_MESSAGE_PWMRESPONSE_H
