// Generated by gencpp from file pi_car/StringRequest.msg
// DO NOT EDIT!


#ifndef PI_CAR_MESSAGE_STRINGREQUEST_H
#define PI_CAR_MESSAGE_STRINGREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pi_car
{
template <class ContainerAllocator>
struct StringRequest_
{
  typedef StringRequest_<ContainerAllocator> Type;

  StringRequest_()
    : input()  {
    }
  StringRequest_(const ContainerAllocator& _alloc)
    : input(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _input_type;
  _input_type input;





  typedef boost::shared_ptr< ::pi_car::StringRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pi_car::StringRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StringRequest_

typedef ::pi_car::StringRequest_<std::allocator<void> > StringRequest;

typedef boost::shared_ptr< ::pi_car::StringRequest > StringRequestPtr;
typedef boost::shared_ptr< ::pi_car::StringRequest const> StringRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pi_car::StringRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pi_car::StringRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pi_car::StringRequest_<ContainerAllocator1> & lhs, const ::pi_car::StringRequest_<ContainerAllocator2> & rhs)
{
  return lhs.input == rhs.input;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pi_car::StringRequest_<ContainerAllocator1> & lhs, const ::pi_car::StringRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pi_car

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pi_car::StringRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pi_car::StringRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pi_car::StringRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pi_car::StringRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pi_car::StringRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pi_car::StringRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pi_car::StringRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "39e92f1778057359c64c7b8a7d7b19de";
  }

  static const char* value(const ::pi_car::StringRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x39e92f1778057359ULL;
  static const uint64_t static_value2 = 0xc64c7b8a7d7b19deULL;
};

template<class ContainerAllocator>
struct DataType< ::pi_car::StringRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pi_car/StringRequest";
  }

  static const char* value(const ::pi_car::StringRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pi_car::StringRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string input\n"
;
  }

  static const char* value(const ::pi_car::StringRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pi_car::StringRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.input);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StringRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pi_car::StringRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pi_car::StringRequest_<ContainerAllocator>& v)
  {
    s << indent << "input: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.input);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PI_CAR_MESSAGE_STRINGREQUEST_H
